name: Minecraft VM Scheduler

on:
  schedule:
    # Encender: 09:05 España/Italia (07:05 UTC)
    - cron: "5 7 * * *"

    # Apagar: 01:05 España/Italia (23:05 UTC)
    - cron: "5 23 * * *"

  workflow_dispatch:
    inputs:
      action:
        description: "Accion"
        required: true
        default: "start"
        type: choice
        options:
          - start
          - stop

permissions:
  id-token: write
  contents: read

jobs:
  minecraft-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 960c8a8f-8118-4e03-b902-750d11decd09
          tenant-id: 7c9c71d7-00f9-476d-8d05-f51abd4ec22a
          subscription-id: 05e51831-a1a8-48ff-91c9-7af5ba5b2de1

      - name: Ejecutar accion de la VM
        run: |
          # Si se pulsa manualmente desde GitHub
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            ACTION="${{ github.event.inputs.action }}"
          else
            # Evaluar la hora actual en hora peninsular (0-23)
            HORA=$(TZ="Europe/Madrid" date +%-H)
            echo "Hora local detectada: $HORA"
            
            # Si corre entre las 00:00 y las 04:00 -> APAGAR
            if [ "\(HORA" -ge 0 ] && [ "\)HORA" -le 4 ]; then
              ACTION="stop"
            # Si corre entre las 08:00 y las 12:00 -> ENCENDER
            elif [ "\(HORA" -ge 8 ] && [ "\)HORA" -le 12 ]; then
              ACTION="start"
            else
              ACTION="none"
            fi
          fi

          echo "Accion a realizar: $ACTION"

          if [ "$ACTION" = "start" ]; then
            echo "Iniciando VM..."
            az vm start --resource-group MC-SERVER --name mc-vm
          elif [ "$ACTION" = "stop" ]; then
            echo "Desasignando/Apagando VM..."
            az vm deallocate --resource-group MC-SERVER --name mc-vm
          else
            echo "Fuera de rango programado, no se hace nada."
          fi
