name: Minecraft VM Scheduler

on:
  schedule:
    # Encender todos los días a las 10:15 hora de Italia
    - cron: "15 10 * * *"
      timezone: "Europe/Rome"

    # Apagar todos los días a las 02:15 hora de Italia
    - cron: "15 2 * * *"
      timezone: "Europe/Rome"

  workflow_dispatch:
    inputs:
      action:
        description: "Acción"
        required: true
        default: "start"
        type: choice
        options:
          - start
          - stop

permissions:
  id-token: write
  contents: read

jobs:
  minecraft-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: 960c8a8f-8118-4e03-b902-750d11decd09
          tenant-id: 7c9c71d7-00f9-476d-8d05-f51abd4ec22a
          subscription-id: 05e51831-a1a8-48ff-91c9-7af5ba5b2de1

      - name: Start Minecraft VM
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'start') ||
          (github.event_name == 'schedule' && github.event.schedule == '15 10 * * *')
        run: |
          echo "Iniciando Minecraft VM..."
          az vm start \
            --resource-group MC-SERVER \
            --name mc-vm

      - name: Stop Minecraft VM
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'stop') ||
          (github.event_name == 'schedule' && github.event.schedule == '15 2 * * *')
        run: |
          echo "Apagando Minecraft VM..."
          az vm deallocate \
            --resource-group MC-SERVER \
            --name mc-vm
